server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  application:
    name: truck-fleet-management

fipe:
  api:
    base:
      url: https://parallelum.com.br/fipe/api/v1/caminhoes

logging:
  level:
    org.springframework.web: DEBUG